# Generated by Django 2.2.5 on 2020-01-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Devise')),
                ('country', models.CharField(max_length=70, verbose_name='Pays')),
                ('iso', models.CharField(max_length=3, verbose_name='ISO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monnaie',
            },
        ),
    ]
