# -*- coding: utf-8 -*-
# pylint: disable=missing-class-docstring,invalid-name
# Generated by Django 2.2.5 on 2020-01-14 12:02
"""
Data migration, for the countries currencies, into the travelget postgreSQL database.
"""

import json
from django.db import migrations

from xconverter.migrations.tools.deserializer import load_json, json_to_model


def _populate_tables(choices, model_name, field):
    """Create all the choice names instances into the model table."""
    for choice, _ in choices:
        field_ = {}
        field_[field] = choice
        choice_name = model_name(**field_)
        choice_name.save()


def fill_currency(apps, _):
    """Filling the Currency table with all the countries currencies."""
    # To get the historical version of the model using the app registry.
    Currency = apps.get_model("xconverter", "Currency")

    # Filling the Currency table.
    CURRENCY_DATA = load_json("xconverter/currencies.json")

    for country in CURRENCY_DATA:
        CURRENCY_DATA_JSON = json.dumps(CURRENCY_DATA[country])
        json_to_model(CURRENCY_DATA_JSON, Currency)


def reverse_fill_currency(apps, _):
    """Reversed fill_currency function by deleting all the data."""
    # To get the historical version of the model using the app registry.
    Currency = apps.get_model("xconverter", "Currency")

    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [("xconverter", "0001_initial")]

    operations = [
        migrations.RunPython(fill_currency, reverse_code=reverse_fill_currency)
    ]
