# Generated by Django 2.2.5 on 2020-01-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='draft.Category', verbose_name='Catégorie'),
        ),
    ]
