# Generated by Django 2.2.5 on 2020-01-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dépenses avant le départ'), (2, 'Transport international'), (3, 'Transport local'), (4, 'Hébergement'), (5, 'Nourriture'), (6, 'Visites'), (7, 'Activités'), (8, 'Souvenirs'), (9, 'Divers')], verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xconverter.Currency', verbose_name='Monnaie'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='draft.Draft', verbose_name='Budget prévisionnel'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.PaymentType', verbose_name='Type de paiement'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='place',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Lieu'),
        ),
    ]
