# -*- coding: utf-8 -*-
# pylint: disable=invalid-name,missing-class-docstring,missing-module-docstring
# Generated by Django 2.2.5 on 2020-01-30 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("wallet", "0001_initial"), ("expenses", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="payment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="wallet.PaymentType",
                verbose_name="Type de paiement",
            ),
        )
    ]
