# Generated by Django 2.2.5 on 2020-01-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20200124_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/<django.db.models.fields.related.ForeignKey>%d/%m/%Y', verbose_name='Photo de la facture'),
        ),
    ]
