# Generated by Django 2.2.5 on 2020-01-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20200124_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/<function get_upload_path at 0x108a78dc0>%d/%m/%Y', verbose_name='Photo de la facture'),
        ),
    ]
