# Generated by Django 2.2.5 on 2020-01-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20200124_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='<function get_upload_path at 0x10c6e9dc0>/%d/%m/%Y', verbose_name='Photo de la facture'),
        ),
    ]
