# Generated by Django 2.2.5 on 2020-01-24 12:42

from django.db import migrations, models
import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20200124_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=expenses.models.get_upload_path, verbose_name='Photo de la facture'),
        ),
    ]
