# -*- coding: utf-8 -*-
# pylint: disable=invalid-name,missing-class-docstring,missing-module-docstring
# Generated by Django 2.2.5 on 2020-01-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("draft", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_name",
                    models.CharField(max_length=30, verbose_name="Nom du portefeuille"),
                ),
                (
                    "payment_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Achat par carte bancaire Visa"),
                            (2, "Achat par carte bancaire MasterCard"),
                            (3, "Paiement en liquide avec le porte-monnaie"),
                            (4, "Paiement par chèque de voyage"),
                            (
                                5,
                                "Paiement ou virement d'un compte Paypal, ApplePay, bancaire, etc.",
                            ),
                        ],
                        verbose_name="Type de portefeuille",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "EUR"),
                            ("USD", "USD"),
                            ("GBP", "GBP"),
                            ("CAD", "CAD"),
                            ("CHF", "CHF"),
                            ("AUD", "AUD"),
                        ],
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                ("balance", models.PositiveSmallIntegerField(verbose_name="Solde")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="draft.Draft",
                        verbose_name="budget prévisionnel",
                    ),
                ),
            ],
            options={"verbose_name": "Portefeuille"},
        )
    ]
