# -*- coding: utf-8 -*-
# pylint: disable=invalid-name,missing-class-docstring,missing-module-docstring
# Generated by Django 2.2.5 on 2020-01-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("draft", "__first__"), ("xconverter", "0002_auto_20200114_1302")]

    operations = [
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_name",
                    models.CharField(max_length=30, verbose_name="Nom du portefeuille"),
                ),
                (
                    "payment_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Carte bancaire Visa"),
                            (2, "Carte bancaire MasterCard"),
                            (3, "Porte-monnaie"),
                            (4, "Chèque de voyage"),
                            (
                                5,
                                "Paiement ou virement d'un compte Paypal, ApplePay, bancaire, etc.",
                            ),
                        ],
                        verbose_name="Type de portefeuille",
                    ),
                ),
                ("balance", models.PositiveIntegerField(verbose_name="Solde")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="xconverter.Currency",
                        verbose_name="Devise",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="draft.Draft",
                        verbose_name="budget prévisionnel",
                    ),
                ),
            ],
            options={"verbose_name": "Portefeuille"},
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Nom de la banque de retrait",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="Lieu"
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Montant")),
                (
                    "rate",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Taux de change (si vous l'avez)",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="xconverter.Currency",
                        verbose_name="Devise",
                    ),
                ),
                (
                    "payment_type_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals_to_wallet",
                        to="wallet.PaymentType",
                        verbose_name="Porte-monnaie crédité",
                    ),
                ),
                (
                    "payment_type_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_card_withdrawals",
                        to="wallet.PaymentType",
                        verbose_name="Carte bancaire débitée",
                    ),
                ),
            ],
            options={"verbose_name": "Retrait"},
        ),
        migrations.CreateModel(
            name="Change",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changer",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Banque ou changeur",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="Lieu"
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Montant")),
                ("rate", models.FloatField(verbose_name="Taux de change")),
                ("date", models.DateField(verbose_name="Date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changed_currencies",
                        to="xconverter.Currency",
                        verbose_name="Devise reçue",
                    ),
                ),
                (
                    "currency_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes_currencies",
                        to="xconverter.Currency",
                        verbose_name="Devise à changer",
                    ),
                ),
                (
                    "payment_type_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes_to_wallet",
                        to="wallet.PaymentType",
                        verbose_name="Porte-monnaie de la devise reçue",
                    ),
                ),
                (
                    "payment_type_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_for_changes",
                        to="wallet.PaymentType",
                        verbose_name="Porte-monnaie de la devise à changer",
                    ),
                ),
            ],
            options={"verbose_name": "Change de devises"},
        ),
    ]
