# -*- coding: utf-8 -*-
# pylint: disable=invalid-name,missing-class-docstring,missing-module-docstring
# Generated by Django 2.2.5 on 2020-01-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("draft", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="Nom du portefeuille"),
                ),
                (
                    "money_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Carte bancaire Visa (compte rattaché)"),
                            (2, "Carte bancaire MasterCard (compte rattaché)"),
                            (3, "Porte-monnaie"),
                            (4, "Chèque de voyage"),
                            (5, "Compte Paypal, ApplePay, etc."),
                        ],
                        verbose_name="Type de portefeuille",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "EUR"),
                            ("USD", "USD"),
                            ("GBP", "GBP"),
                            ("CAD", "CAD"),
                            ("CHF", "CHF"),
                            ("AUD", "AUD"),
                        ],
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                ("balance", models.PositiveSmallIntegerField(verbose_name="Solde")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="draft.Draft",
                        verbose_name="budget prévisionnel",
                    ),
                ),
            ],
            options={"verbose_name": "Portefeuille"},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Retrait ATM"),
                            (2, "Retrait DAB"),
                            (3, "Achat par carte bancaire"),
                            (4, "Virement bancaire"),
                            (5, "Paiement en liquide"),
                            (6, "Paiement Paypal, ApplePay, etc."),
                            (7, "Crédit sur un compte"),
                        ],
                        verbose_name="Type de transaction",
                    ),
                ),
                ("rate", models.FloatField(verbose_name="Taux de change")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wallet.Wallet",
                        verbose_name="portefeuille",
                    ),
                ),
            ],
            options={"verbose_name": "Transaction"},
        ),
    ]
