# Generated by Django 2.2.5 on 2020-01-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Retrait ATM'), (2, 'Retrait DAB'), (3, 'Achat par carte bancaire'), (4, 'Paiement en liquide'), (5, 'Paiement par chèque de voyage'), (6, 'Virement bancaire, Paypal, ApplePay, etc.'), (7, 'Crédit')], verbose_name='Type de transaction'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='money_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Carte bancaire Visa (compte rattaché)'), (2, 'Carte bancaire MasterCard (compte rattaché)'), (3, 'Porte-monnaie'), (4, 'Chèque de voyage'), (5, 'Compte Paypal, ApplePay, etc., ou bancaire pour virement')], verbose_name='Type de portefeuille'),
        ),
    ]
