# Generated by Django 2.2.5 on 2020-01-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Carte bancaire Visa'), (2, 'Carte bancaire MasterCard'), (3, 'Porte-monnaie'), (4, 'Chèque de voyage'), (5, "Paiement ou virement d'un compte Paypal, ApplePay, bancaire, etc.")], verbose_name='Type de portefeuille'),
        ),
    ]
