# Generated by Django 2.2.5 on 2020-01-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200117_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='draft.Draft', verbose_name='budget prévisionnel'),
        ),
    ]
