# Generated by Django 2.2.5 on 2020-01-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_change_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='balance',
            field=models.PositiveIntegerField(verbose_name='Solde'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Montant'),
        ),
    ]
